[project]
name = "web-scraping"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "pandas>=2.3.3",
    "playwright>=1.58.0",
    "requests>=2.32.5",
]
